# Generated by Django 6.0.4 on 2026-04-15 09:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service')], default='available', max_length=15)),
                ('cash_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('max_withdrawal', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ATMRestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_added', models.DecimalField(decimal_places=2, max_digits=15)),
                ('restocked_by', models.CharField(max_length=100)),
                ('restocked_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='atm.atm')),
            ],
        ),
    ]
